<table class="table table-striped">
    <thead>
        <tr>
            <th>API</th>
            <th>Versions</th>
        </tr>
    </thead>
    <tbody><?php foreach ($this->apis as $api): 
        $name = $api['name']; ?>
        <tr>
            <td><?php echo $this->escapeHtml($name) ?></td>
            <td><pre><?php 
                $view     = $this;
                $versions = array_map(function ($version) use ($name, $view) {
                    return sprintf(
                        '<a href="/swagger/%s-v%s">v%s</a>',
                        $view->escapeUrl($name),
                        $view->escapeUrl($version),
                        $view->escapeHtml($version)
                    );
                }, $api['versions']);
                echo implode('&nbsp;|&nbsp;', $versions);
            ?></td>
        </tr>
    <?php endforeach; ?></tbody>
</table>
